#!/bin/sh

SELF=$(basename "$0")

# we redirect stderr to eat the 'route' spew generated by system_resolvconf_generate()
/usr/local/bin/php -- "$SELF" "$@" 2>/dev/null <<-'EOP'
<?php

/*
 * gateway_action.php
 * helper to enable/disable gateways
 *
 * TODO:
 * - use can_delete_disable_gateway_item() for safety
 * - transition to on-device Nexus API?
 *
 */

$self = $argv[1];
array_shift($argv);

require_once("config.inc");
require_once("gwlb.inc");

refresh_gateways();
$a_gateways = get_gateways(GW_CACHE_INDEXED);
//print_r($a_gateways);

function show_help() {
	global $self, $a_gateways;
	echo "Usage: {$self} <gateway> <action> [--force]\n";
	echo "  <gateway>  can be index# or name\n";
	echo "  <action>   one of: enable, disable\n";
	echo "  --force    apply action even if gateway is already in desired state\n\n";
	echo "  configured gateways:\n";
	foreach ($a_gateways as $idx => $gw) {
		printf("    [%s] %s%s - %s (%s)\n", $idx, $gw["name"], ($gw["disabled"] ? " (disabled)" : ""), $gw["gateway"], $gw["interface"]);
	}
	exit();
}

$opts = [];
$args = [];
foreach ($argv as $i => $arg) {
    if ($i === 0) continue;
    if ($arg[0] === '-') {
        $opts[] = $arg;
    } else {
        $args[] = $arg;
    }
}

// process args
if ($argc < 3 || !empty(array_intersect($opts, ['-h', '--help']))) { show_help(); }
$selected_gw = $argv[1];
$action = $argv[2];
$force = !empty(array_intersect($opts, ['-f', '--force']));
$gwid = filter_var($selected_gw, FILTER_VALIDATE_INT, ["options" => ["min_range" => 0]]);

if ($gwid === false) {
	// get by name
	foreach ($a_gateways as $idx => $gw) {
		if (($gw["name"] ?? null) === $selected_gw) {
			$gwid = $idx;
			break;
		}
	}
} else { 
	// get by index
	$gwid = intval($selected_gw);
}

if (empty($gwid) || !isset($a_gateways[$gwid])) {
	echo "invalid gateway: {$selected_gw}\n";
	exit(1);
}

$gwname = $a_gateways[$gwid]["name"];

switch ($action) {
	case "enable":
		if (isset($a_gateways[$gwid]["disabled"]) || $force) {
			echo "enabling {$gwname}\n";
			gateway_set_enabled($gwname, true);
		} else {
			echo "$gwname already enabled\n";
			exit(0);
		}
		break;
	case "disable":
		if (!isset($a_gateways[$gwid]["disabled"]) || $force) {
			echo "disabling {$gwname}\n";
			gateway_set_enabled($gwname, false);
		} else {
			echo "$gwname already disabled\n";
			exit(0);
		}
		break;
	default:
		echo "invalid action: {$action}\n";
		exit(1);
}

mark_subsystem_dirty("staticroutes");
if (write_config("{$self}: $action $gwname")) {
	$retval = 0;
	setup_gateways_monitor();
	$retval |= system_routing_configure();
	$retval |= system_resolvconf_generate();
	$retval |= filter_configure();
	send_event("service reload dyndnsall");
	if ($retval == 0) {
		clear_subsystem_dirty("staticroutes");
	}
}

?>
EOP
